use anyhow::anyhow;

pub static LANDMARK_HAYSTACK: &[&str] = &[
	"S",
	"N",
	"Ba",
	"Pg",
	"A",
	"Gn",
	"B",
	"ANS",
	"CoR",
	"CoL",
	"IncR",
	"IncL",
	"GoL",
	"GoR",
	"LO_R",
	"LO_L",
	"InS",
	"InInf",
	"InS-InInf",
	"MolSupR",
	"MolSupL",
	"MolInfR",
	"MolInfL",
	"OrR",
	"OrL",
	"Sella",
	"Nasion",
	"Basion",
	"Pogonion",
	"A point",
	"Point A",
	"Gnathion",
	"B point",
	"Point B",
	"Anterior nasal spine",
	"Condylion, R",
	"Condylion, L",
	"Incisura, R",
	"Incisura, L",
	"Gonion, L",
	"Gonion, R",
	"Latero-Orbital point, R",
	"Latero-Orbital point, L",
	"Midpoint upper incisors",
	"Midpoint lower incisors",
	"Midpoint between incisors",
	"Cusp upper molar, R",
	"Cusp upper molar, L",
	"Cusp lower molar, R",
	"Cusp lower molar, L",
	"Orbitale, R",
	"Orbitale, L",
];

#[derive(Debug, Clone, Copy, PartialEq,Ord, PartialOrd, Eq)]
pub enum Landmark {
	S,
	N,
	Ba,
	Pg,
	A,
	Gn,
	B,
	ANS,
	CoR,
	CoL,
	IncR,
	IncL,
	GoL,
	GoR,
	LOR,
	LOL,
	InS,
	InInf,
	InSInInf,
	MolSupR,
	MolSupL,
	MolInfR,
	MolInfL,
	OrR,
	OrL,
}

impl std::str::FromStr for Landmark {
	type Err = anyhow::Error;

	fn from_str(s: &str) -> Result<Self, Self::Err> {
		match s {
			"S" | "Sella" => Ok(Self::S),
			"N" | "Nasion" => Ok(Self::N),
			"Ba" | "Basion" => Ok(Self::Ba),
			"Pg" | "Pogonion" => Ok(Self::Pg),
			"A" | "A point" | "Point A" => Ok(Self::A),
			"Gn" | "Gnathion" => Ok(Self::Gn),
			"B" | "B point" | "Point B" => Ok(Self::B),
			"ANS" | "Anterior nasal spine" => Ok(Self::ANS),
			"CoR" | "Condylion, R" => Ok(Self::CoR),
			"CoL" | "Condylion, L" => Ok(Self::CoL),
			"IncR" | "Incisura, R" => Ok(Self::IncR),
			"IncL" | "Incisura, L" => Ok(Self::IncL),
			"GoL" | "Gonion, L" => Ok(Self::GoL),
			"GoR" | "Gonion, R" => Ok(Self::GoR),
			"LO_R" | "Latero-Orbital point, R" => Ok(Self::LOR),
			"LO_L" | "Latero-Orbital point, L" => Ok(Self::LOL),
			"InS" | "Midpoint upper incisors" => Ok(Self::InS),
			"InInf" | "Midpoint lower incisors" => Ok(Self::InInf),
			"InS-InInf" | "Midpoint between incisors" => Ok(Self::InSInInf),
			"MolSupR" | "Cusp upper molar, R" => Ok(Self::MolSupR),
			"MolSupL" | "Cusp upper molar, L" => Ok(Self::MolSupL),
			"MolInfR" | "Cusp lower molar, R" => Ok(Self::MolInfR),
			"MolInfL" | "Cusp lower molar, L" => Ok(Self::MolInfL),
			"OrR" | "Orbitale, R" => Ok(Self::OrR),
			"OrL" | "Orbitale, L" => Ok(Self::OrL),
			_ => Err(anyhow!("Failed to parse landmark: '{}'", s)),
		}
	}
}

impl Landmark {
	pub fn as_str(&self) -> &'static str {
		match self {
			Self::S => "S",
			Self::N => "N",
			Self::Ba => "Ba",
			Self::Pg => "Pg",
			Self::A => "A",
			Self::Gn => "Gn",
			Self::B => "B",
			Self::ANS => "ANS",
			Self::CoR => "CoR",
			Self::CoL => "CoL",
			Self::IncR => "IncR",
			Self::IncL => "IncL",
			Self::GoL => "GoL",
			Self::GoR => "GoR",
			Self::LOR => "LO_R",
			Self::LOL => "LO_L",
			Self::InS => "InS",
			Self::InInf => "InInf",
			Self::InSInInf => "InS-InInf",
			Self::MolSupR => "MolSupR",
			Self::MolSupL => "MolSupL",
			Self::MolInfR => "MolInfR",
			Self::MolInfL => "MolInfL",
			Self::OrR => "OrR",
			Self::OrL => "OrL",
		}
	}
}

impl std::fmt::Display for Landmark {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		write!(f, "{}", self.as_str())
	}
}
