[application]

[bundle]
identifier = "jacob.steentoft.slicer.toolbox"
publisher = "Jacob Steentoft"

[web.app]

# HTML title tag content
title = "Slicer Toolbox"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
